package com.bitsco.vks.report.constant;

import java.util.HashMap;
import java.util.Map;

public interface ReportConstant {
    interface PACKAGE {
        public static final String PKG_REPORT_BOOK_01 = "PKG_REPORT_BOOK_01";
        public static final String PKG_REPORT_BOOK_02 = "PKG_REPORT_BOOK_02";
        public static final String PKG_REPORT_BOOK_03 = "PKG_REPORT_BOOK_03";
        public static final String PKG_REPORT_BOOK_04 = "PKG_REPORT_BOOK_04";
        public static final String PKG_REPORT_BOOK_05 = "PKG_REPORT_BOOK_05";
        public static final String PKG_REPORT_BOOK_06 = "PKG_REPORT_BOOK_06";
        public static final String PKG_REPORT_BOOK_07 = "PKG_REPORT_BOOK_07";
        public static final String PKG_REPORT_BOOK_08 = "PKG_REPORT_BOOK_08";
        public static final String PKG_REPORT_BOOK_09 = "PKG_REPORT_BOOK_09";
        public static final String PKG_REPORT_BOOK_10 = "PKG_REPORT_BOOK_10";
        public static final String PKG_REPORT_BOOK_11 = "PKG_REPORT_BOOK_11";
        public static final String PKG_REPORT_BOOK_12 = "PKG_REPORT_BOOK_12";
        public static final String PKG_REPORT_BOOK_13 = "PKG_REPORT_BOOK_13";
        public static final String PKG_REPORT_BOOK_14 = "PKG_REPORT_BOOK_14";
        public static final String PKG_REPORT_BOOK_15 = "PKG_REPORT_BOOK_15";
        public static final String PKG_REPORT_BOOK_16 = "PKG_REPORT_BOOK_16";
        public static final String PKG_REPORT_BOOK_17 = "PKG_REPORT_BOOK_17";
        public static final String PKG_REPORT_BOOK_18 = "PKG_REPORT_BOOK_18";
        public static final String PKG_REPORT_BOOK_19 = "PKG_REPORT_BOOK_19";
        public static final String PKG_REPORT_BOOK_20 = "PKG_REPORT_BOOK_20";
        public static final String PKG_REPORT_BOOK_21 = "PKG_REPORT_BOOK_21";
        public static final String PKG_REPORT_BOOK_22 = "PKG_REPORT_BOOK_22";
        public static final String PKG_REPORT_BOOK_23 = "PKG_REPORT_BOOK_23";
        public static final String PKG_REPORT_BOOK_24 = "PKG_REPORT_BOOK_24";
        public static final String PKG_REPORT_BOOK_25 = "PKG_REPORT_BOOK_25";
        public static final String PKG_REPORT_BOOK_26 = "PKG_REPORT_BOOK_26";
        public static final String PKG_REPORT_BOOK_27 = "PKG_REPORT_BOOK_27";
        public static final String PKG_REPORT_BOOK_28 = "PKG_REPORT_BOOK_28";
        public static final String PKG_REPORT_BOOK_29 = "PKG_REPORT_BOOK_29";
        public static final String PKG_REPORT_BOOK_30 = "PKG_REPORT_BOOK_30";
        public static final String PKG_REPORT_BOOK_31 = "PKG_REPORT_BOOK_31";
        public static final String PKG_REPORT_BOOK_32 = "PKG_REPORT_BOOK_32";
        public static final String PKG_REPORT_BOOK_66 = "PKG_REPORT_BOOK_66";
        public static final String PKG_DASHBOARD_01 = "PKG_DASHBOARD_01";
        public static final String PKG_DASHBOARD_02 = "PKG_DASHBOARD_02";
        public static final String PKG_DASHBOARD_03 = "PKG_DASHBOARD_03";
        public static final String PKG_DASHBOARD_04 = "PKG_DASHBOARD_04";
    }

    interface FUNCTION {
        public static final String FUNC_QUERYING = "FUNC_QUERYING";
        public static final String FUNC_QUERYING_ONE_YEAR = "func_querying_one_year";
        public static final String FUNC_QUERYING_DASHBOARD = "FUNC_QUERYING_DASHBOARD";
        public static final String FUNC_QUERYING_DETAIL = "FUNC_QUERYING_DETAIL";

        public static final String FN_INSERT_UPDATE_NOTE = "FN_INSERT_UPDATE_NOTE";
    }

    interface TABLE {
        public static final String REPORT_DETAIL = "REPORT_DETAIL";
        public static final String REPORT_PERIOD_DETAIL = "REPORT_PERIOD_DETAIL";
        public static final String REPORT_INPUT = "REPORT_INPUT";
        public static final String REPORT_PERIOD_INPUT = "REPORT_PERIOD_INPUT";
        public static final String REQUEST_REPORT = "REQUEST_REPORT";
        public static final String REQUEST_PERIOD_REPORT = "REQUEST_PERIOD_REPORT";
        public static final String NOTEBOOKS = "NOTEBOOKS";
        public static final String RP_BOOK_07 = "RP_BOOK_07";
    }

    interface SEQUENCE {
        public static final String SQ_REPORT_DETAIL = "SQ_REPORT_DETAIL";
        public static final String SQ_REPORT_PERIOD_DETAIL = "SQ_REPORT_PERIOD_DETAIL";
        public static final String SQ_REPORT_INPUT = "SQ_REPORT_INPUT";
        public static final String SQ_REPORT_PERIOD_INPUT = "SQ_REPORT_PERIOD_INPUT";
        public static final String SQ_REQUEST_REPORT = "SQ_REQUEST_REPORT";
        public static final String SQ_REQUEST_PERIOD_REPORT = "SQ_REQUEST_PERIOD_REPORT";
        public static final String SQ_NOTE_BOOK = "SQ_NOTE_BOOK";
        public static final String SQ_BOOK_07 = "SQ_BOOK_07";
    }

    interface REQUEST_REPORT {
        interface REPORT_CODE {
            public static final String REPORT_01 = "01";
            public static final String REPORT_02 = "02";
            public static final String REPORT_03 = "03";
            public static final String REPORT_04 = "04";
            public static final String REPORT_05 = "05";
            public static final String REPORT_06 = "06";
            public static final String REPORT_07 = "07";
            public static final String REPORT_08 = "08";
            public static final String REPORT_09 = "09";
            public static final String REPORT_10 = "10";
            public static final String REPORT_11 = "11";
            public static final String REPORT_12 = "12";
            public static final String REPORT_33 = "33";
        }

        interface STATUS {
            public static final int DELETE = 0;
            public static final int NEW = 1;
            public static final int PROCESSING = 2;
            public static final int SUCCESS = 3;
            public static final int ERROR = 4;
        }

        interface STATUS_RESPONSE {
            public static final String SUCCESS = "0000";
            public static final int OKE = 200;
        }

        interface DESCRIPTION_COLUMN {
            public static final Map<Integer, String> REPORT_01 = new HashMap<Integer, String>() {{
                put(1, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố còn lại của kỳ trước");
                put(2, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố được cơ quan có thẩm quyền phục hồi giải quyết (lý do tạm đình chỉ không còn)");
                put(3, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(4, "                 - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(5, "                 - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(6, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố mới nhận");
                put(7, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(8, "                 - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(9, "                 - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(10, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố nơi khác chuyển đến");
                put(11, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(12, "	    - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(13, "	    - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(14, "	    - Số tố giác, tin báo... các cơ quan được giao nhiệm vụ tiến hành một số hoạt động điều tra chuyển đến ");
                put(15, "	    - Số kiến nghị khởi tố được các cơ quan nhà nước khác (thanh tra, kiểm toán...) chuyển đến ");
                put(16, "Trong đó: - Số kiến nghị khởi tố do các cơ quan nhà nước chuyển đến VKS");
                put(17, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố chuyển đi nơi khác");
                put(18, "Tổng số tố giác, tin báo về tội phạm, kiến nghị khởi tố phải giải quyết");
                put(19, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(20, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(21, "                - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(22, "                - Số tố giác, tin báo... về tội phạm cơ quan điều tra của công an nhân dân phải giải quyết");
                put(23, "Số tố giác, tin báo về tội phạm và kiến nghị khởi tố đã giải quyết");
                put(24, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quyết định khởi tố vụ án hình sự");
                put(25, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(26, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(27, "                - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(28, "                - Do cơ quan điều tra của công an nhân dân khởi tố");
                put(29, "                - Số tố giác, tin báo... đã khởi tố theo yêu cầu của VKS");
                put(30, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quyết định không khởi tố vụ án hình sự");
                put(31, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(32, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(33, "                - Số tố giác, tin báo... các tội phạm khácvề chức vụ");
                put(34, "                - Do cơ quan điều tra của công an nhân dân quyết định không khởi tố");
                put(35, "                - Số tố giác, tin báo...  chuyển xử lý hành chính hoặc xử lý bằng biện pháp khác");
                put(36, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố tạm đình chỉ giải quyết trong kỳ thống kê ");
                put(37, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(38, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(39, "                - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(40, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quá hạn khi ra quyết định khởi tố, quyết định không khởi tố hoặc tạm đình chỉ ");
                put(41, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(42, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(43, "                - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(44, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố chưa giải quyết xong");
                put(45, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(46, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(47, "                - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(48, "                - Thuộc thẩm quyền cơ quan điều tra của công an nhân dân");
                put(49, "                - Số đã quá thời hạn giải quyết");
                put(50, "Trong đó: - Cơ quan điều tra của công an nhân dân");
                put(51, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố VKS yêu cầu kiểm tra, xác minh");
                put(52, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố Viện kiểm sát gia hạn thời hạn giải quyết");
                put(53, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố tạm đình chỉ giải quyết tính đến cuối kỳ thống kê ");
                put(54, "Trong đó: - Số tố giác, tin báo... các tội phạm tham nhũng");
                put(55, "                - Số tố giác, tin báo... các tội phạm về kinh tế");
                put(56, "                - Số tố giác, tin báo... các tội phạm khác về chức vụ");
                put(57, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố do VKS trực tiếp giải quyết");
                put(58, "Trong đó: - Số tố giác, tin báo... còn lại của kỳ trước");
                put(59, "                - Số tố giác, tin báo... được phục hồi giải quyết (lý do tạm đình chỉ không còn)");
                put(60, "                - Số tố giác, tin báo... mới thụ lý");
                put(61, "                - Số tố giác, tin báo... đã quyết định khởi tố vụ án hình sự");
                put(62, "                - Số tố giác, tin báo... đã quyết định không khởi tố vụ án hình sự");
                put(63, "                - Số tố giác, tin báo... tạm đình chỉ giải quyết trong kỳ thống kê ");
                put(64, "                - Số tố giác, tin báo ... chưa giải quyết xong");
                put(65, "Trong đó: - Số đã quá thời hạn giải guyết");
                put(66, "                - Số tố giác, tin báo... tạm đình chỉ giải quyết tính đến cuối kỳ thống kê ");
                put(67, "Số quyết định VKS huỷ bỏ quyết định tạm đình chỉ việc giải quyết tố giác, tin báo về tội phạm, kiến nghị khởi tố ");
                put(68, "Trong đó: - Do cơ quan điều tra của công an nhân dân quyết định tạm đình chỉ				");
                put(69, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố VKS yêu cầu CQĐT, cơ quan được giao nhiệm vụ tiến hành 1 số hoạt động điều tra tiếp nhận, kiểm tra việc tiếp nhận, giải quyết và thông báo kết quả cho VKS");
                put(70, "Số lần trực tiếp kiểm sát việc giải quyết tố giác, tin báo về tội phạm, kiến nghị khởi tố của CQĐT, cơ quan được giao nhiệm vụ tiến hành một số hoạt động điều tra ");
                put(71, "Số bản kiến nghị yêu cầu CQĐT, cơ quan được giao nhiệm vụ tiến hành một số hoạt động điều tra khắc phục vi phạm pháp luật và xử lý người vi phạm trong việc tiếp nhận, giải quyết tố giác, tin báo về tội phạm, kiến nghị khởi tố ");
                put(72, "Số bản kiến nghị được chấp nhận");
                put(73, "Số bản kiến nghị không được chấp nhận");
                put(74, "Số bản kiến nghị yêu cầu cơ quan, tổ chức, cá nhân có liên quan khắc phục những sơ hở, thiếu sót trong hoạt động quản lý để phòng ngừa vi phạm pháp luật và tội phạm");
            }};
            public static final Map<Integer, String> REPORT_07 = new HashMap<Integer, String>() {{
                put(1, "Số tạm giữ còn lại của kỳ trước");
                put(2, "Số người mới bị tạm giữ");
                put(3, "Trong đó: - Người bị giữ trong trường hợp khẩn cấp");
                put(4, "	 - Người bị bắt trong trường hợp phạm tội quả tang");
                put(5, "	 - Người bị bắt theo quyết định truy nã");
                put(6, "	 - Người phạm tội tự thú");
                put(7, "	 - Người phạm tội đầu thú");
                put(8, "Số nơi khác chuyển đến");
                put(9, "Số chuyển đi nơi khác");
                put(10, "Tổng số người bị tạm giữ");
                put(11, "Số đã giải quyết");
                put(12, "Trong đó: - Số khởi tố chuyển tạm giam");
                put(13, "	 - Số khởi tố áp dụng biện pháp ngăn chặn khác");
                put(14, "	 - Số truy nã chuyển tạm giam");
                put(15, "	 - Số tạm giữ được trả tự do");
                put(16, "	  Trong đó: + Số người Viện kiểm sát hủy bỏ quyết định tạm giữ");
                put(17, "	             + Số người Viện kiểm sát không phê chuẩn quyết định gia hạn tạm giữ");
                put(18, "	             + Số người Viện kiểm sát không phê chuẩn lệnh bắt người bị giữ trong trường hợp khẩn cấp");
                put(19, "	             + Số người không đủ căn cứ khởi tố bị can");
                put(20, "	             + Số người trả tự do trong thời gian chờ kết quả giám định, đinh giá");
                put(21, "	             + Số người trả tự do do bị hại hoặc người đại diện của bị hại rút đơn yêu cầu khởi tố");
                put(22, "	  - Số tạm giữ được VKS trả tự do theo quy định của  luật tổ chức VKSND, luật thi hành tạm giữ, tạm giam");
                put(23, "Số quá hạn tạm giữ đã giải quyết");
                put(24, "Số người tạm giữ chết");
                put(25, "Trong đó: - Chết do bệnh lý");
                put(26, "	 - Chết do tự sát");
                put(27, "	 - Chết do nguyên nhân khác");
                put(28, "Số người tạm giữ trốn trong kỳ thống kê");
                put(29, "Trong đó: - Số trốn trong kỳ thống kê chưa bắt lại được");
                put(30, "Số người còn tạm giữ đến cuối kỳ thống kê");
                put(31, "Trong đó: - Số quá hạn tạm giữ");
                put(32, "Số tạm giam còn lại của kỳ trước");
                put(33, "Số người mới bị tạm giam");
                put(34, "Trong đó: - Số người tạm giữ chuyển tạm giam");
                put(35, "	 - Số người cơ quan điều tra ra lệnh bắt để tạm giam");
                put(36, "	 - Số người VKS ra lệnh bắt để tạm giam");
                put(37, "	 - Số người tòa án sơ thẩm ra lệnh bắt để tạm giam");
                put(38, "	 - Số người bị kết án đang tại ngoại tự nguyện hoặc bị áp giải để thi hành án");
                put(39, "Số nơi khác chuyển đến");
                put(40, "Trong đó: - Số chuyển đến để làm thủ tục chấp hành án");
                put(41, "	 - Số chuyển đến để xét xử phúc thẩm");
                put(42, "Số chuyển đi nơi khác");
                put(43, "Trong đó: - Số chuyển đi để làm thủ tục chấp hành án");
                put(44, "	  - Số chuyển đi để xét xử phúc thẩm");
                put(45, "Tổng số người bị tạm giam");
                put(46, "Số người bị tạm giam đã giải quyết");
                put(47, "Trong đó: - Huỷ bỏ biện pháp tạm giam");
                put(48, "	 - Thay thế bằng biện pháp ngăn chặn khác");
                put(49, "	 - Trả tự do khi bị can có quyết định đình chỉ");
                put(50, "	     Trong đó: Số trả tự do chuyển xử lý hành chính, xử lý kỷ luật");
                put(51, "	 - Hội đồng xét xử trả tự do");
                put(52, "	     Trong đó: + Bị cáo không phạm tội");
                put(53, "	               + Bị cáo được miễn trách nhiệm hình sự hoặc được miễn hình phạt");
                put(54, "	               + Bị cáo bị xử phạt bằng hình phạt không phải là hình phạt tù");
                put(55, "	               + Bị cáo bị xử phạt tù nhưng cho hưởng án treo");
                put(56, "	               + Bị cáo bị phạt tù mà thời hạn phạt tù bằng hoặc ngắn hơn thời gian đã bị tạm giam");
                put(57, "	 - Trả tự do khi hết án trong thời gian kháng cáo, kháng nghị");
                put(58, "	 - Hết thời hạn tù trong thời gian chờ quyết định chuyển đi chấp hành án");
                put(59, "	 - Số tạm giam được VKS trả tự do theo quy định của  luật tổ chức VKSND, luật thi hành tạm giữ, tạm giam");
                put(60, "	 - Số người đang chờ đưa đi chấp hành án phạt tù được tạm đình chỉ chấp hành án");
                put(61, "	 - Số người chuyển chấp hành án");
                put(62, "	 - Số đã thi hành án tử hình");
                put(63, "	 - bắt buộc chữa bệnh");
                put(64, "Tổng số người đang áp dụng biện pháp bắt buộc chữa bệnh tính đến cuối kỳ thống kê");
                put(65, "Số quá hạn tạm giam đã giải quyết");
                put(66, "Trong đó: - Thuộc trách nhiệm của cơ quan điều tra");
                put(67, "	 - Thuộc trách nhiệm của Viện kiểm sát");
                put(68, "	 - Thuộc trách nhiệm của Tòa án");
                put(69, "Số người bị tạm giam chết");
                put(70, "Trong đó: - Chết do tự sát");
                put(71, "	 - Chết do bệnh lý");
                put(72, "	 - Chết do các nguyên nhân khác");
                put(73, "Số người bị tạm giam trốn chưa bắt lại được tính đến cuối kỳ thống kê");
                put(74, "Trong đó: - Số trốn trong kỳ thống kê chưa bắt lại được");
                put(75, "Số người còn bị tạm giam tính đến cuối kỳ thống kê");
                put(76, "Trong đó: - Số còn tạm giam trong giai đoạn điều tra");
                put(77, "	 - Số còn tạm giam trong giai đoạn truy tố");
                put(78, "	 - Số còn tạm giam trong giai đoạn xét xử sơ thẩm");
                put(79, "	 - Số còn tạm giam trong giai đoạn xét xử phúc thẩm");
                put(80, "	 - Số còn tạm giam chờ chuyển đến nơi chấp hành án");
                put(81, "	 - Số còn tạm giam đã quá hạn");
                put(82, "	     Trong đó: + Thuộc trách nhiệm của cơ quan điều tra");
                put(83, "	               + Thuộc trách nhiệm của Viện kiểm sát");
                put(84, "	               + Thuộc trách nhiệm của Tòa án");
                put(85, "	 - Số bị án tử hình đang tạm giam");
                put(86, "Số lần Viện kiểm sát trực tiếp kiểm sát nhà tạm giữ có kết luận");
                put(87, "Số lần Viện kiểm sát kiểm sát đột xuất nhà tạm giữ");
                put(88, "Số lần Viện kiểm sát trực tiếp kiểm sát trại tạm giam có kết luận");
                put(89, "Số lần Viện kiểm sát kiểm sát đột xuất trại tạm giam");
                put(90, "Số văn bản Viện kiểm sát yêu cầu tự kiểm tra việc tạm giữ, tạm giam");
                put(91, "Số lần Viện kiểm sát yêu cầu cung cấp hồ sơ, tài liệu liên quan đến quản lý, thi hành tạm giữ, tạm giam");
                put(92, "Số lần Viện kiểm sát yêu cầu thông báo tình hình tạm giữ, tạm giam");
                put(93, "Số lần Viện kiểm sát yêu cầu trả lời về quyết định, biện pháp hoặc việc làm vi phạm pháp luật trong việc tạm giữ, tạm giam");
                put(94, "Số hồ sơ tạm giữ, tạm giam VKS đã kiểm sát");
                put(95, "Số lần VKS gặp hởi người bị tạm giữ, tạm giam");
                put(96, "Số bản kiến nghị yêu cầu khắc phục vi phạm trong việc tạm giữ, tạm giam");
                put(97, "Số bản kiến nghị được chấp nhận sửa chữa");
                put(98, "Số bản kiến nghị không được chấp nhận sửa chữa");
                put(99, "Số bản kháng nghị yêu cầu khắc phục vi phạm trong việc tạm giữ, tạm giam");
                put(100, "Trong đó: - Số kháng nghị của VKS với cơ quan cùng cấp yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc tạm giữ, tạm giam");
                put(101, "	  - Số kháng nghị của VKS với cơ quan cùng cấp yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc tạm giữ, tạm giam");
                put(102, "	  - Số kháng nghị của VKS với cơ quan cấp dưới yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc tạm giữ, tạm giam");
                put(103, "	  - Số kháng nghị của VKS với cơ quan cấp dưới yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc tạm giữ, tạm giam");
                put(104, "Số bản kháng nghị được chấp nhận sửa chữa");
                put(105, "Số bản kháng nghị không được chấp nhận sửa chữa");
                put(106, "Số cuộc kiểm sát việc thực hiện kiến nghị, kháng nghị, yêu cầu đã có kết luận");
                put(107, "Số người bị kết án, pháp nhân thương mại bị kết án chưa ra quyết định thi hành án kỳ trước chuyển qua");
                put(108, "Trong đó: - Số pháp nhân thương mại bị kết án");
                put(109, "Số người bị kết án, pháp nhân thương mại bị kết án mới phát sinh trong kỳ chưa ra quyết định thi hành án");
                put(110, "Trong đó: - Số pháp nhân thương mại bị kết án");
                put(111, "Số người bị kết án, pháp nhân thương mại bị kết án nhận uỷ thác ra quyết định thi hành án");
                put(112, "Trong đó: - Số pháp nhân thương mại bị kết án");
                put(113, "Số người bị kết án, pháp nhân thương mại bị kết án uỷ thác đi nơi khác ra quyết định thi hành án");
                put(114, "Trong đó: - Số pháp nhân thương mại bị kết án");
                put(115, "Tổng số người bị kết án, pháp nhân thương mại bị kết án Tòa án phải ra quyết định thi hành án");
                put(116, "Trong đó: - Số người bị kết án tù chung thân phải ra quyết định thi hành án");
                put(117, "	  - Số người bị kết án tù có thời hạn phải ra quyết định thi hành án");
                put(118, "	  - Số pháp nhân thương mại bị kết án phải ra quyết định thi hành án");
                put(119, "Số người bị kết án chết khi chưa có quyết định thi hành án");
                put(120, "Số người chưa có quyết định thi hành án phạm tội mới");
                put(121, "Trong đó: - Số người bị tuyên phạt ctkgg");
                put(122, "	  - Số người bị tuyên phạt tù nhưng cho hưởng án treo");
                put(123, "	  - Số người bị tuyên phạt tù có thời hạn đang tại ngoại");
                put(124, "Số người bị kết án, pháp nhân thương mại bị kết án Tòa án đã ra quyết định thi hành án trong kỳ thống kê");
                put(125, "Trong đó: - Số người bị kết án tù chung thân đã ra quyết định thi hành án");
                put(126, "	  - Số người bị kết án tù có thời hạn đã ra quyết định thi hành án");
                put(127, "	  - Số pháp nhân thương mại bị kết án đã ra quyết định thi hành án");
                put(128, "Số người bị kết án, pháp nhân thương mại bị kết án Tòa án chưa ra quyết định thi hành án");
                put(129, "Trong đó: - Đã quá hạn luật định");
                put(130, "	  - Số người bị kết án tù chung thân chưa ra quyết định thi hành án");
                put(131, "	  - Số người bị kết án tù có thời hạn chưa ra quyết định thi hành án");
                put(132, "	  - Số pháp nhân thương mại bị kết án chưa ra quyết định thi hành án");
                put(133, "Số người chấp hành án đã có quyết định thi hành án của kỳ thống kê trước nhưng chưa đưa đi thi hành án");
                put(134, "Số đã có quyết định thi hành án nơi khác chuyển đến");
                put(135, "Số đã có quyết định thi hành án chuyển đi nơi khác");
                put(136, "Tổng số người chấp hành án đã có quyết định thi hành án phải đưa đi thi hành án");
                put(137, "Số người chấp hành án được Tòa án giám đốc thẩm huỷ án, tuyên không phạm tội");
                put(138, "Số người chấp hành án được Tòa án tái thẩm huỷ án, tuyên không phạm tội");
                put(139, "Số người chấp hành án được hoãn chấp hành án trong kỳ thống kê");
                put(140, "Số người chấp hành án được tạm đình chỉ chấp hành án trong kỳ thống kê");
                put(141, "Số người chấp hành án được miễn chấp hành hình phạt");
                put(142, "Trong đó: - Số người được miễn chấp hành hình phạt tù");
                put(143, "Số người chấp hành án được hưởng thời hiệu");
                put(144, "Trong đó: - Số người chấp hành án phạt tù được hưởng thời hiệu");
                put(145, "Số người chấp hành án chết sau khi có quyết định thi hành án nhưng chưa đi thi hành án");
                put(146, "Số người chấp hành án trốn sau khi có quyết định thi hành án nhưng chưa đi thi hành án trong kỳ thống kê");
                put(147, "Số người đã có quyết định thi hành án phạm tội mới");
                put(148, "Trong đó: - Số người bị tuyên phạt CTKGG");
                put(149, "	  - Số người bị tuyên phạt tù nhưng cho hưởng án treo");
                put(150, "	  - Số người bị tuyên phạt tù có thời hạn đang tại ngoại");
                put(151, "Số người chấp hành án đã đi thi hành án");
                put(152, "Trong đó: - Số người chấp hành án tù chung thân đã đi thi hành án");
                put(153, "	  - Số người chấp hành án tù có thời hạn đã đi thi hành án");
                put(154, "Số người chấp hành án đã có quyết định thi hành án còn lại chưa đi thi hành án");
                put(155, "Trong đó: - Số người chấp hành án tù chung thân chưa đi thi hành án");
                put(156, "	         Trong đó: + Số người chấp hành án tù chung thân chưa đi thi hành án trốn chưa bắt lại tính đến cuối kỳ thống kê");
                put(157, "	  - Số người chấp hành án tù có thời hạn chưa đi thi hành án");
                put(158, "	         Trong đó: + Số người chấp hành án tù có thời hạn chưa đi thi hành án trốn chưa bắt lại tính đến cuối kỳ thống kê");
                put(159, "	                   + Số người chấp hành án tù có thời hạn đang được tạm đình chỉ chấp hành án tính đến cuối kỳ thống kê");
                put(160, "Tổng số người được hoãn chấp hành án");
                put(161, "Trong đó: - Số người được hoãn chấp hành án chết trong thời gian được hoãn chấp hành án");
                put(162, "	  - Số người được hoãn chấp hành án được miễn chấp hành hình phạt trong thời gian được hoãn chấp hành án");
                put(163, "	  - Số người được hoãn chấp hành án bị tòa án có thẩm quyền hủy quyết định hoãn chấp hành án");
                put(164, "Số đã hết thời hạn hoãn chấp hành án");
                put(165, "Trong đó: - Số đã đi chấp hành án");
                put(166, "	  - Số chưa đi chấp hành án");
                put(167, "Tổng số người chấp hành án phạt tù có thời hạn đang được hoãn chấp hành án tính đến cuối kỳ thống kê");
                put(168, "Số người bị kết án đã có quyết định thi hành án kỳ thống kê trước chuyển sang");
                put(169, "Số người bị kết án mới có quyết định thi hành án");
                put(170, "Tổng số người bị kết án tử hình đã có quyết định thi hành án");
                put(171, "Số người bị kết án hoãn thi hành án tử hình trong kỳ thống kê");
                put(172, "Số người bị kết án đã có quyết định thi hành án được giảm xuống hình phạt khác");
                put(173, "Số người bị kết án đã có quyết định thi hành án chết trong kỳ thống kê");
                put(174, "Số người bị kết án đã có quyết định thi hành án trốn trong kỳ thống kê");
                put(175, "Số đã thi hành án tử hình trong kỳ thống kê");
                put(176, "Số người bị kết án đã có quyết định thi hành án còn lại chưa thi hành án tính đến cuối kỳ thống kê");
                put(177, "Trong đó: - Số người được hoãn thi hành án tử hình tính đến cuối kỳ thống kê");
                put(178, "	  - Số người đã có quyết định thi hành án trốn chưa bắt lại tính đến cuối kỳ thống kê");
                put(179, "Số phạm nhân kỳ thống kê trước chuyển sang");
                put(180, "Số phạm nhân mới");
                put(181, "Số nơi khác chuyển đến");
                put(182, "Trong đó: - Số phạm nhân trả trích xuất");
                put(183, "Số chuyển đi nơi khác");
                put(184, "Trong đó: - Số phạm nhân đã trích xuất");
                put(185, "Tổng số phạm nhân");
                put(186, "Trong đó: - Số phạm nhân đã giảm án xuống tù có thời hạn");
                put(187, "Số phạm nhân chết");
                put(188, "Trong đó: - Chết do tự sát");
                put(189, "	  - Chết do bệnh lý");
                put(190, "	  - Chết do các nguyên nhân khác");
                put(191, "Số phạm nhân trốn trong kỳ thống kê chưa bắt lại được");
                put(192, "Số phạm nhân giảm xuống tù có thời hạn đã chấp hành xong");
                put(193, "Trong đó: - Số phạm nhân được đặc xá");
                put(194, "Số phạm nhân được tòa án trả tự do");
                put(195, "Số phạm nhân đang chấp hành án tính đến cuối kỳ thống kê");
                put(196, "Số phạm nhân trốn chưa bắt lại được tính đến cuối kỳ thống kê");
                put(197, "Số phạm nhân kỳ thống kê trước chuyển sang");
                put(198, "Số phạm nhân đến chấp hành án do bị tòa án hủy quyết định tha tù trước thời hạn có điều kiện và buộc người đó tiếp tục thi hành án");
                put(199, "Số phạm nhân mới");
                put(200, "Số nơi khác chuyển đến");
                put(201, "Trong đó: - Số phạm nhân trả trích xuất");
                put(202, "Số chuyển đi nơi khác");
                put(203, "Trong đó: - Số phạm nhân đã trích xuất");
                put(204, "Tổng số phạm nhân");
                put(205, "Số phạm nhân đã chấp hành án xong");
                put(206, "Trong đó: - Số phạm nhân được đặc xá");
                put(207, "Số phạm nhân được tha tù trước thời hạn có điều kiện");
                put(208, "Số phạm nhân được VKS trả tự do theo quy định của luật tổ chức VKSND, luật thi hành án hình sự");
                put(209, "Số phạm nhân được tòa án trả tự do");
                put(210, "Số phạm nhân chết");
                put(211, "Trong đó: - Chết do tự sát");
                put(212, "	  - Chết do bệnh lý");
                put(213, "	  - Chết do các nguyên nhân khác");
                put(214, "Số phạm nhân trốn chưa bắt lại được tính đến cuối kỳ thống kê");
                put(215, "Trong đó: - Số phạm nhân trốn trong kỳ thống kê chưa bắt lại được");
                put(216, "Số phạm nhân áp dụng biện pháp bắt buộc chữa bệnh trong kỳ thống kê");
                put(217, "Tổng số phạm nhân đang áp dụng biện pháp bắt buộc chữa bệnh tính đến cuối  kỳ thống kê");
                put(218, "Số phạm nhân đang chấp hành án tính đến cuối kỳ thống kê");
                put(219, "Trong đó: - Số phạm nhân đang chấp hành án tại trại tạm giam");
                put(220, "	  - Số phạm nhân đang chấp hành án tại nhà tạm giữ");
                put(221, "Số phạm nhân được tạm đình chỉ chấp hành án trong kỳ thống kê");
                put(222, "Số tạm đình chỉ đã tiếp tục thi hành án");
                put(223, "Số tạm đình chỉ được miễn chấp hành án");
                put(224, "Số tạm đình chỉ chết");
                put(225, "Số tạm đình chỉ trốn trong kỳ thống kê chưa bắt lại được");
                put(226, "Tổng số tạm đình chỉ trốn đến cuối kỳ thống kê chưa bắt lại được");
                put(227, "Tổng số phạm nhân được tạm đình chỉ tính đến cuối kỳ thống kê");
                put(228, "Trong đó: - Số đã hết thời hạn tạm đình chỉ");
                put(229, "Số còn lại của kỳ trước");
                put(230, "Số mới");
                put(231, "Số nơi khác chuyển đến");
                put(232, "Số chuyển đi nơi khác");
                put(233, "Tổng số");
                put(234, "Số đã chấp hành xong");
                put(235, "Số tòa án tuyên hủy bản án đã tuyên phạt án treo");
                put(236, "Số phạm tội mới");
                put(237, "Số án treo vi phạm nghĩa vụ bị buộc phải chấp hành hình phạt tù");
                put(238, "Số bị tòa án tuyên hủy án treo chuyển sang tù giam");
                put(239, "Số đang thi hành án treo chết");
                put(240, "Số đang chấp hành án tính đến cuối kỳ thống kê");
                put(241, "Số còn lại của kỳ trước");
                put(242, "Số mới");
                put(243, "Tổng số");
                put(244, "Số đã trục xuất");
                put(245, "Số còn lại chưa trục xuất tính đến cuối kỳ thống kê");
                put(246, "Số còn lại của kỳ trước");
                put(247, "Số mới");
                put(248, "Số nơi khác chuyển đến");
                put(249, "Số chuyển đi nơi khác");
                put(250, "Tổng số");
                put(251, "Số đã chấp hành xong");
                put(252, "Số được tòa án giám đốc thẩm, tái thẩm tuyên hủy bản án đã tuyên phạt ctkgg");
                put(253, "Số phạm tội mới");
                put(254, "Số đang thi hành án phạt cải tạo không giam giữ chết");
                put(255, "Số đang thi hành án tính đến cuối kỳ thống kê");
                put(256, "Số còn lại của kỳ trước");
                put(257, "Số mới");
                put(258, "Tổng số");
                put(259, "Số đã chấp hành xong");
                put(260, "Số đang chấp hành án tính đến cuối kỳ thống kê");
                put(261, "Số còn lại của kỳ trước");
                put(262, "Số mới");
                put(263, "Tổng số");
                put(264, "Số đã chấp hành xong");
                put(265, "Số đang chấp hành án tính đến cuối kỳ thống kê");
                put(266, "Số còn lại của kỳ trước");
                put(267, "Số mới");
                put(268, "Tổng số");
                put(269, "Số đã chấp hành xong");
                put(270, "Số đang chấp hành án tính đến cuối kỳ thống kê");
                put(271, "Số còn lại của kỳ trước");
                put(272, "Số mới");
                put(273, "Tổng số");
                put(274, "Số đã chấp hành xong");
                put(275, "Số đang chấp hành án tính đến cuối kỳ thống kê");
                put(276, "Số pháp nhân thương mại chấp hành án chưa thi hành xong của kỳ thống kê trước chuyển sang");
                put(277, "Số pháp nhân thương mại chấp hành án mới phát sinh trong kỳ thống kê");
                put(278, "Tổng số pháp nhân thương mại chấp hành án");
                put(279, "Số pháp nhân thương mại đã chấp hành án xong");
                put(280, "Số pháp nhân thương mại chưa chấp hành án xong");
                put(281, "Trong đó: - Số pháp nhân thương mại không chấp hành quyết định thi hành án");
                put(282, "Số pháp nhân thương mại chấp hành án chưa thi hành xong của kỳ thống kê trước chuyển sang");
                put(283, "Số pháp nhân thương mại chấp hành án mới phát sinh trong kỳ thống kê");
                put(284, "Tổng số pháp nhân thương mại chấp hành án");
                put(285, "Số pháp nhân thương mại đã chấp hành án xong");
                put(286, "Số pháp nhân thương mại chưa chấp hành án xong");
                put(287, "Trong đó: - Số pháp nhân thương mại không chấp hành quyết định thi hành án");
                put(288, "Số pháp nhân thương mại chấp hành án chưa thi hành xong của kỳ thống kê trước chuyển sang");
                put(289, "Số pháp nhân thương mại chấp hành án mới phát sinh trong kỳ thống kê");
                put(290, "Tổng số pháp nhân thương mại chấp hành án");
                put(291, "Số pháp nhân thương mại đã chấp hành án xong");
                put(292, "Số pháp nhân thương mại chưa chấp hành án xong");
                put(293, "Trong đó: - Số pháp nhân thương mại không chấp hành quyết định thi hành án");
                put(294, "Số pháp nhân thương mại chấp hành án chưa thi hành xong của kỳ thống kê trước chuyển sang");
                put(295, "Số pháp nhân thương mại chấp hành án mới phát sinh trong kỳ thống kê");
                put(296, "Tổng số pháp nhân thương mại chấp hành án");
                put(297, "Số pháp nhân thương mại đã chấp hành án xong");
                put(298, "Số pháp nhân thương mại chưa chấp hành án xong");
                put(299, "Trong đó: - Số pháp nhân thương mại không chấp hành quyết định thi hành án");
                put(300, "Số pháp nhân thương mại chấp hành án chưa thi hành xong của kỳ thống kê trước chuyển sang");
                put(301, "Số pháp nhân thương mại chấp hành án mới phát sinh trong kỳ thống kê");
                put(302, "Tổng số pháp nhân thương mại chấp hành án");
                put(303, "Số pháp nhân thương mại đã chấp hành án xong");
                put(304, "Số pháp nhân thương mại chưa chấp hành án xong");
                put(305, "Trong đó: - Số pháp nhân thương mại không chấp hành quyết định thi hành án");
                put(306, "Số quyết định của tòa án có vi phạm");
                put(307, "Số người bị kết án Viện kiểm sát yêu cầu tòa án ra quyết định thi hành án");
                put(308, "Số người bị kết án án tòa án đã ra quyết định thi hành án theo yêu cầu của Viện kiểm sát");
                put(309, "Số người chấp hành án Viện kiểm sát đề nghị hoãn thi hành án");
                put(310, "Số người chấp hành án tòa án đã ra quyết định hoãn chấp hành án theo  đề nghị của VKS");
                put(311, "Số người chấp hành án Viện kiểm sát đề nghị miễn chấp hành hình phạt");
                put(312, "Số người chấp hành án tòa án đã ra quyết định miễn chấp hành hình phạt theo đề nghị của Viện kiểm sát");
                put(313, "Trong đó: - Số người chấp hành án phạt tù được miễn chấp hành án theo đề nghị của Viện kiểm sát");
                put(314, "Số người chấp hành án Viện kiểm sát đề nghị xét hưởng thời hiệu");
                put(315, "Số người chấp hành án tòa án đã ra quyết định được hưởng thời hiệu theo đề nghị của VKS");
                put(316, "Trong đó: - Số người chấp hành án phạt tù được hưởng thời hiệu theo đề nghị của VKS");
                put(317, "Số người chấp hành án Viện kiểm sát đề nghị đình chỉ thi hành án");
                put(318, "Số người chấp hành án tòa án đã ra quyết định đình chỉ thi hành án theo đề nghị của VKS");
                put(319, "Số văn bản Viện kiểm sát yêu cầu Tòa án tự kiểm tra và thông báo kết quả cho VKS");
                put(320, "Số văn bản Viện kiểm sát yêu cầu Tòa án cung cấp tài liệu");
                put(321, "Số phạm nhân Viện kiểm sát đề nghị tạm đình chỉ chấp hành hình phạt tù");
                put(322, "Số người chấp hành án Viện kiểm sát đề nghị miễn chấp hành hình phạt còn lại trong thời gian người chấp hành án đang được tạm đình chỉ chấp hành hình phạt tù");
                put(323, "Số người chấp hành án Viện kiểm sát yêu cầu công an  áp giải");
                put(324, "Số người chấp hành án công an đã áp giải theo yêu cầu của VKS");
                put(325, "Số người chấp hành án Viện kiểm sát yêu cầu công an  truy nã");
                put(326, "Số người chấp hành án công an đã truy nã theo yêu cầu của VKS");
                put(327, "Số văn bản Viện kiểm sát yêu cầu cơ quan thi hành án hình sự cùng cấp tự kiểm tra và thông báo kết quả cho Viện kiểm sát");
                put(328, "Số văn bản Viện kiểm sát yêu cầu cơ quan thi hành án hình sự cấp dưới tự kiểm tra và thông báo kết quả cho Viện kiểm sát");
                put(329, "Số văn bản Viện kiểm sát yêu cầu cơ quan thi hành án hình sự cùng cấp cung cấp tài liệu");
                put(330, "Số văn bản Viện kiểm sát yêu cầu cơ quan thi hành án hình sự cấp dưới cung cấp tài liệu");
                put(331, "Số lần Viện kiểm sát trực tiếp kiểm sát cơ quan thi hành án hình sự cùng cấp đã ban hành kết luận");
                put(332, "Số lần Viện kiểm sát trực tiếp kiểm sát cơ quan thi hành án hình sự cấp dưới đã ban hành kết luận");
                put(333, "Số lần kiểm sát đột xuất cơ quan thi hành án hình sự cùng cấp");
                put(334, "Số lần kiểm sát đột xuất cơ quan thi hành án hình sự cấp dưới");
                put(335, "Số hồ sơ thi hành án VKS đã kiểm sát");
                put(336, "Số bản kiến nghị cơ quan thi hành án hình sự cùng cấp");
                put(337, "Số bản kiến nghị được chấp nhận sửa chữa");
                put(338, "Số bản kiến nghị không được chấp nhận sửa chữa");
                put(339, "Số bản kiến nghị cơ quan thi hành án hình sự cấp dưới");
                put(340, "Số bản kiến nghị được chấp nhận sửa chữa");
                put(341, "Số bản kiến nghị không được chấp nhận sửa chữa");
                put(342, "Số bản kháng nghị cơ quan thi hành án cùng cấp");
                put(343, "Trong đó: - Số bản kháng nghị của VKS yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(344, "	  - Số bản kháng nghị của VKS yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(345, "Số bản kháng nghị được chấp nhận sửa chữa");
                put(346, "Số bản kháng nghị không được chấp nhận sửa chữa");
                put(347, "Số bản kháng nghị cơ quan thi hành án cấp dưới");
                put(348, "Trong đó: - Số bản kháng nghị của VKS yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(349, "	  - Số bản kháng nghị của VKS yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(350, "Số bản kháng nghị được chấp nhận sửa chữa");
                put(351, "Số bản kháng nghị không được chấp nhận sửa chữa");
                put(352, "Số lần VKS trực tiếp kiểm sát trực tiếp trại giam, phân trại quản lý phạm nhân thuộc trại tạm giam");
                put(353, "Số hồ sơ phạm nhân VKS đã kiểm sát");
                put(354, "Số lần VKS gặp hỏi phạm nhân");
                put(355, "Số bản kiến nghị đối với trại giam, trại tạm giam trong việc quản lý phạm nhân");
                put(356, "Số bản kiến nghị được chấp nhận sửa chữa");
                put(357, "Số bản kiến nghị không được chấp nhận sửa chữa");
                put(358, "Số bản kháng nghị đối với trại giam, trại tạm giam trong việc quản lý phạm nhân");
                put(359, "Trong đó: - Số bản kháng nghị của VKS với cơ quan cùng cấp yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc quản lý và giáo dục người chấp hành án phạt tù");
                put(360, "	  -  Số bản kháng nghị của VKS với cơ quan cùng cấp yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc quản lý và giáo dục người chấp hành án phạt tù");
                put(361, "	  - Số bản kháng nghị của VKS với cơ quan cấp dưới yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc quản lý và giáo dục người chấp hành án phạt tù");
                put(362, "	  - Số bản kháng nghị của VKS với cơ quan cấp dưới yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc quản lý và giáo dục người chấp hành án phạt tù");
                put(363, "Số bản kháng nghị được chấp nhận sửa chữa");
                put(364, "Số bản kháng nghị không được chấp nhận sửa chữa");
                put(365, "Số phạm nhân Viện kiểm sát kiểm sát việc xét giảm thời hạn chấp hành hình phạt tù");
                put(366, "Số phạm nhân VKS đề nghị đưa ra khỏi danh sách xét giảm thời hạn chấp hành án phạt tù");
                put(367, "Trong đó: - Số phạm nhân VKS đề nghị đưa ra khỏi danh sách xét giảm thời hạn chấp hành án phạt tù được chấp nhận");
                put(368, "Số phạm nhân được xét giảm thời hạn chấp hành hình phạt tù");
                put(369, "Số phạm nhân Viện kiểm sát đề nghị giảm thời hạn chấp hành hình phạt tù khác với đề nghị của cơ quan công an");
                put(370, "Trong đó: - Tòa án chấp nhận đề nghị của Viện kiểm sát");
                put(371, "Số phạm nhân Viện kiểm sát kiểm sát việc đề nghị tha tù trước thời hạn có điều kiện");
                put(372, "Số phạm nhân Viện kiểm sát đề nghị không chấp nhận tha tù trước thời hạn có điều kiện");
                put(373, "Trong đó: - Tòa án chấp nhận đề nghị của Viện kiểm sát");
                put(374, "Số phạm nhân Viện kiểm sát kiểm sát việc lập hồ sơ đề nghị đặc xá");
                put(375, "Số phạm nhân Viện kiểm sát yêu cầu đưa ra khỏi danh sách đặc xá");
                put(376, "Trong đó: - Số phạm nhân Viện kiểm sát yêu cầu đưa ra khỏi danh sách đặc xá được chấp nhận");
                put(377, "Số văn bản Viện kiểm sát yêu cầu trại giam, phân trại tự kiểm tra công tác thi hành án hình sự và thông báo kết quả cho Viện kiểm sát");
                put(378, "Số văn bản Viện kiểm sát yêu cầu  ủy ban nhân dân cấp xã, cơ quan, tổ chức tự kiểm tra công tác thi hành án hình sự và thông báo kết quả cho Viện kiểm sát");
                put(379, "Số lần VKS trực tiếp kiểm sát ủy ban nhân dân cấp xã, cơ quan, tổ chức trong thi hành án hình sự đã ban hành kết luận");
                put(380, "Số bản kiến nghị ủy ban nhân dân cấp xã, cơ quan, tổ chức");
                put(381, "Số bản kiến nghị được chấp nhận sửa chữa");
                put(382, "Số bản kiến nghị không được chấp nhận sửa chữa");
                put(383, "Số bản kháng nghị ủy ban nhân dân cấp xã, cơ quan, tổ chức");
                put(384, "Số bản kháng nghị được chấp nhận sửa chữa");
                put(385, "Số bản kháng nghị không được chấp nhận sửa chữa");
                put(386, "Số người Viện kiểm sát tham gia xét rút ngắn thời gian thử thách đối với án treo");
                put(387, "Số người VKS đề nghị đưa ra khỏi danh sách xét rút ngắn thời gian thử thách đối với án treo");
                put(388, "Trong đó: - Số người VKS đề nghị đưa ra khỏi danh sách xét rút ngắn thời gian thử thách đối với án treo được chấp nhận");
                put(389, "Số người được rút ngắn thời gian thử thách đối với án treo");
                put(390, "Số người Viện kiểm sát tham gia xét giảm thời hạn chấp hành hình phạt cải tạo không giam giữ");
                put(391, "Số người VKS đề nghị đưa ra khỏi danh sách xét giảm thời hạn chấp hành hình phạt cải tạo không giam giữ");
                put(392, "Trong đó: - Số người VKS đề nghị đưa ra khỏi danh sách xét giảm thời hạn chấp hành hình phạt cải tạo không giam giữ được chấp nhận");
                put(393, "Số người được xét giảm thời hạn chấp hành hình phạt cải tạo không giam giữ");
                put(394, "Số người Viện kiểm sát tham gia xét rút ngắn thời gian thử thách đối với tha tù trước thời hạn có điều kiện");
                put(395, "Số người VKS đề nghị đưa ra khỏi danh sách xét rút ngắn thời gian thử thách đối với tha tù trước thời hạn có điều kiện");
                put(396, "Trong đó: - Số người VKS đề nghị đưa ra khỏi danh sách xét rút ngắn thời gian thử thách đối với tha tù trước thời hạn được chấp nhận");
                put(397, "Số người được tha tù trước thời hạn có điều kiện được rút ngắn thời gian thử thách");
                put(398, "Số bản kiến nghị yêu cầu Tòa án khắc phục vi phạm");
                put(399, "Số bản kiến nghị được chấp nhận sửa chữa");
                put(400, "Số bản kiến nghị không được chấp nhận sửa chữa");
                put(401, "Số bản kháng nghị các quyết định  của Tòa án");
                put(402, "Trong đó: - Số bản kháng nghị của VKS với tòa án cùng cấp yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(403, "	  - Số bản kháng nghị của VKS với tòa án cùng cấp yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(404, "	  - Số bản kháng nghị của VKS với tòa án cấp dưới yêu cầu đình chỉ việc thi hành các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(405, "	  - Số bản kháng nghị của VKS với tòa án cấp dưới yêu cầu hủy bỏ các quyết định vi phạm pháp luật trong việc thi hành án hình sự");
                put(406, "Số bản kháng nghị được chấp nhận sửa chữa");
                put(407, "Số bản kháng nghị không được chấp nhận sửa chữa");
                put(408, "Số cuộc kiểm sát việc thực hiện kiến nghị, kháng nghị, yêu cầu đã có kết luận");
            }};
            public static final Map<Integer, String> REPORT_08 = new HashMap<Integer, String>() {{
                put(1, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố còn lại của kỳ trước");
                put(2, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố được CQĐT phục hồi giải quyết (lý do tạm đình chỉ không còn)");
                put(3, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(4, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố mới nhận");
                put(5, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(6, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố nơi khác chuyển đến");
                put(7, "Trong đó: - Số tố giác, tin báo... do cơ quan điều tra khác chuyển đến");
                put(8, "        - Số kiến nghị khởi tố được các cơ quan nhà nước khác (thanh tra, kiểm toán...) chuyển đến");
                put(9, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố chuyển đi nơi khác");
                put(10, "tổng Số tố giác, tin báo về tội phạm, kiến nghị khởi tố phải giải quyết");
                put(11, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(12, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quyết định khởi tố vụ án hình sự");
                put(13, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(14, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quyết định không khởi tố vụ án hình sự");
                put(15, "Trong đó: - Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(16, "        - Số tố giác, tin báo.... quyết định không khởi tố chuyển xử lý hành chính hoặc xử lý bằng biện pháp khác");
                put(17, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố tạm đình chỉ giải quyết trong kỳ thống kê");
                put(18, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(19, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quá hạn khi ra quyết định khởi tố, quyết định không khởi tố hoặc tạm đình chỉ");
                put(20, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(21, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố chưa giải quyết xong");
                put(22, "Trong đó: - Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(23, "        - Số đã quá thời hạn giải guyết");
                put(24, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố tạm đình chỉ giải quyết tính đến cuối kỳ thống kê");
                put(25, "Trong đó: Số tố giác, tin báo... về tội phạm tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
            }};
            public static final Map<Integer, String> REPORT_09 = new HashMap<Integer, String>() {{
                put(1, "Số vụ án còn lại của kỳ trước");
                put(2, "Số vụ án nhận để điều tra lại");
                put(3, "Số vụ án điều tra bổ sung");
                put(4, "Số vụ án tạm đình chỉ phục hồi điều tra trong kỳ thống kê");
                put(5, "Số bị can còn lại của kỳ trước");
                put(6, "Số bị can nhận để điều tra lại");
                put(7, "Số bị can điều tra bổ sung");
                put(8, "Số bị can tạm đình chỉ phục hồi điều tra trong kỳ thống kê");
                put(9, "Số vụ án mới khởi tố");
                put(10, "Trong đó:	 - Số vụ án tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(11, "	 - Số vụ án áp dụng biện pháp điều tra tố tụng đặc biệt:");
                put(12, "	   Trong đó:  + Ghi âm, ghi hình bí mật");
                put(13, "	              + Nghe điện thoại bí mật");
                put(14, "	              + Thu thập bí mật dữ liệu điện tử");
                put(15, "Số bị can mới khởi tố");
                put(16, "Trong đó:	 - Số bị can phạm tội tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(17, "	 - Số bị can có người bào chữa");
                put(18, "	     Trong đó:  + Luật sư");
                put(19, "	                + Bào chữa viên nhân dân");
                put(20, "	                + Trợ giúp viên pháp lý");
                put(21, "	  - Số bị can là cán bộ của cơ quan công an");
                put(22, "	  - Số bị can là cán bộ của cơ quan kiểm sát");
                put(23, "	  - Số bị can là cán bộ của cơ quan tòa án");
                put(24, "	  - Số bị can là cán bộ của cơ quan thi hành án");
                put(25, "	  - Số bị can là cán bộ của cơ quan khác");
                put(26, "Số vụ án nơi khác chuyển đến");
                put(27, "Số bị can nơi khác chuyển đến");
                put(28, "Số vụ án chuyển đi nơi khác");
                put(29, "Số bị can chuyển đi nơi khác");
                put(30, "Tổng Số vụ án phải điều tra");
                put(31, "Trong đó:	Số vụ án tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(32, "Tổng Số bị can phải điều tra");
                put(33, "Trong đó:	 Số bị can phạm tội tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(34, "Số vụ án kết thúc điều tra đề nghị truy tố");
                put(35, "Trong đó:	 Số vụ án tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(36, "Số bị can kết thúc điều tra đề nghị truy tố");
                put(37, "Trong đó:	 Số bị can phạm tội tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(38, "Số vụ án đình chỉ điều tra");
                put(39, "Trong đó:	 Số vụ án tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(40, "Số bị can đình chỉ điều tra");
                put(41, "Trong đó:	 Số bị can phạm tội tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(42, "Số vụ án tạm đình chỉ điều tra trong kỳ thống kê");
                put(43, "Trong đó:	 Số vụ án tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(44, "Số bị can tạm đình chỉ điều tra trong kỳ thống kê");
                put(45, "Trong đó:	 Số bị can phạm tội tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(46, "tổng Số vụ án VKS tạm đình chỉ tính đến cuối kỳ thống kê");
                put(47, "tổng Số bị can VKS tạm đình chỉ tính đến cuối kỳ thống kê");
                put(48, "Số vụ án còn lại chưa kết thúc điều tra");
                put(49, "Trong đó:	 - Số vụ án tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(50, "	 - Số vụ án chưa kết thúc điều tra đã quá thời hạn luật định");
                put(51, "Số bị can còn lại chưa kết thúc điều tra");
                put(52, "Trong đó:	 Số bị can phạm tội tham nhũng, chức vụ xảy ra trong hoạt động tư pháp");
                put(53, "Số bản kiến nghị của CQĐT yêu cầu cơ quan có thẩm quyền khắc phục những sơ hở thiếu sót trong hoạt động quản lý để phòng ngừa vi phạm pháp luật và tội phạm");
            }};
            public static final Map<Integer, String> REPORT_33 = new HashMap<Integer, String>() {{
                put(1, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố thuộc thẩm quyền không thụ lý");
                put(2, "Trong đó: - Cơ quan điều tra của công an nhân dân");
                put(3, "                 - Cơ quan điều tra của quân đội nhân dân");
                put(4, "                         Trong đó: Cơ quan điều tra của VKSQS trung ương");
                put(5, "                 - Cơ quan điều tra của Viện kiểm sát nhân dân tối cao");
                put(6, "                 - Cơ quan điều tra khác được giao tiến hành một số hoạt động điều tra (hải quan, cảnh sát biển, kiểm lâm...)");
                put(7, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố thụ lý giải quyết không đúng thẩm quyền");
                put(8, "Trong đó: - Cơ quan điều tra của công an nhân dân");
                put(9, "                  - Cơ quan điều tra của quân đội nhân dân");
                put(10, "                          Trong đó: Cơ quan điều tra của VKSQS trung ương");
                put(11, "                  - Cơ quan điều tra của Viện kiểm sát tối cao");
                put(12, "                  - Cơ quan điều tra khác được giao tiến hành một số hoạt động điều tra (hải quan, cảnh sát biển, kiểm lâm...)");
                put(13, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã quá thời hạn khi ra quyết định khởi tố, quyết định không khởi tố hoặc tạm đình chỉ");
                put(14, "Trong đó: Cơ quan điều tra của công an nhân dân");
                put(15, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố Cơ quan có thẩm quyền quyết định tạm đình chỉ việc giải quyết không đúng pháp luật");
                put(16, "Số tố giác, tin báo về tội phạm và kiến nghị khởi tố đã quá thời hạn");
                put(17, "Trong đó: - Cơ quan điều tra của công an nhân dân");
                put(18, "                  - Cơ quan điều tra của quân đội nhân dân");
                put(19, "                   Trong đó: Cơ quan điều tra của VKSQS trung ương");
                put(20, "                  - Cơ quan điều tra của Viện kiểm sát nhân dân tối cao");
                put(21, "                  - Cơ quan điều tra khác được giao tiến hành một số hoạt động điều tra (hải quan, cảnh sát biển, kiểm lâm...)");
                put(22, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố đã ra QĐ giải quyết nhưng không gửi hoặc gửi không đúng thời hạn cho VKS");
                put(23, "Trong đó: - Cơ quan điều tra của công an nhân dân");
                put(24, "                  - Cơ quan điều tra của quân đội nhân dân");
                put(25, "                  - Cơ quan điều tra của Viện kiểm sát nhân dân tối cao");
                put(26, "                  - Cơ quan điều tra khác được giao tiến hành một số hoạt động điều tra (hải quan, cảnh sát biển, kiểm lâm...)");
                put(27, "Số quyết định của Viện kiểm sát huỷ bỏ quyết định tạm đình chỉ việc giải quyết tố giác, tin báo về tội phạm, kiến nghị khởi tố không đúng pháp luật");
                put(28, "Số vụ án VKS ra quyết định huỷ bỏ quyết định không khởi tố vụ án và ra quyết định khởi tố vụ án để điều tra");
                put(29, "Trong đó: - Cơ quan điều tra của công an nhân dân");
                put(30, "                   - Cơ quan điều tra của quân đội nhân dân");
                put(31, "                   - Cơ quan điều tra của Viện kiểm sát nhân dân tối cao");
                put(32, "                   - Cơ quan điều tra khác được giao tiến hành một số hoạt động điều tra (hải quan, cảnh sát biển, kiểm lâm...)");
                put(33, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố xác định đủ căn cứ pháp luật nhưng CQĐT không khởi tố mà VKS không yêu cầu CQĐT khởi tố vụ án hoặc VKS không khởi tố vụ án và yêu cầu điều tra");
                put(34, "Số quyết định của VKS huỷ bỏ quyết định không khởi tố vụ án của CQĐT không có căn cứ pháp luật");
                put(35, "Số tố giác, tin báo về tội phạm, kiến nghị khởi tố có vi phạm khác");
                put(36, "Số lệnh, quyết định trong khởi tố, điều tra có vi phạm");
                put(37, "Số lần vi phạm trong việc thu thập tài liệu, chứng cứ");
                put(38, "Trong đó: - Số lần vi phạm trong thực nghiệm điều tra, nhận dạng, trưng cầu giám định, nhận biết giọng nói, định giá tài sản…");
                put(39, "                  - Số lần vi phạm trong hỏi cung bị can, lấy lời khai người làm chứng");
                put(40, "                  - Số lần vi phạm trong khám nghiệm hiện trường, tử thi…");
                put(41, "Số lần vi phạm trong việc giao nhận các biên bản, tài liệu điều tra, đánh số bút lục... (theo K5 Đ88 BLTTHS)");
                put(42, "Trong đó: Cơ quan điều tra của công an nhân dân");
                put(43, "Số vụ án bị VKS huỷ bỏ việc áp dụng biện pháp điều tra tố tụng đặc biệt do có vi phạm trong quá trình áp dụng");
                put(44, "Số vụ án vi phạm về phục hồi điều tra");
                put(45, "Số lần vi phạm trong việc bảo quản và xử lý vật chứng");
                put(46, "Số lần vi phạm quy định về truy nã bị can");
                put(47, "Số lần vi phạm quy định về bào chữa trong giai đoạn điều tra ");
                put(48, "Số vụ án vi phạm về thời hạn điều tra");
                put(49, "Số lần vi phạm các quy định về thông báo tiếp xúc lãnh sự trong các vụ án liên quan đến người nước ngoài");
                put(50, "Số vụ án VKS ra quyết định huỷ bỏ quyết định khởi tố vụ án hình sự");
                put(51, "Số bị can VKS ra quyết định huỷ bỏ quyết định khởi tố bị can");
                put(52, "Số vụ án VKS ra quyết định huỷ bỏ quyết định thay đổi, bổ sung quyết định khởi tố vụ án hình sự");
                put(53, "Số bị can VKS ra quyết định huỷ bỏ quyết định thay đổi, bổ sung quyết định khởi tố bị can");
                put(54, "Số vụ án VKS ra quyết định huỷ bỏ quyết định nhập, tách vụ án hình sự");
                put(55, "Số vụ án VKS ra quyết định huỷ bỏ quyết định đình chỉ điều tra vụ án");
                put(56, "Số bị can VKS ra quyết định huỷ bỏ quyết định đình chỉ điều tra vụ án đối với bị can");
                put(57, "Số vụ án VKS ra quyết định huỷ bỏ quyết định tạm đình chỉ điều tra vụ án");
                put(58, "Số bị can VKS ra quyết định huỷ bỏ quyết định tạm đình chỉ điều tra vụ án đối với bị can");
                put(59, "Số QĐ của VKS huỷ bỏ QĐ khởi tố vụ án hình sự không có căn cứ pháp luật");
                put(60, "Số bị can VKS vi phạm thời hạn phê chuẩn QĐ khởi tố bị can");
                put(61, "Số vụ án VKS huỷ bỏ việc áp dụng biện pháp điều tra tố tụng đặc biệt không có căn cứ pháp luật");
                put(62, "Số bị can VKS phê chuẩn QĐ khởi tố bị can không có căn cứ pháp luật sau đó phải đình chỉ điều tra do không phạm tội");
                put(63, "Số bị can VKS không phê chuẩn QĐ khởi tố bị can không có căn cứ pháp luật");
                put(64, "Số QĐ của VKS bị VKS cấp trên huỷ bỏ do không có căn cứ pháp luật");
                put(65, "Số lần vi phạm quy định về bảo đảm quyền bào chữa của bị can trong giai đoạn truy tố ");
                put(66, "Số vụ án vi phạm về thời hạn truy tố");
                put(67, "Số vụ án VKS đình chỉ không có căn cứ pháp luật");
                put(68, "Số bị can VKS đình chỉ không có căn cứ pháp luật");
                put(69, "Số vụ án VKS tạm đình chỉ không có căn cứ pháp luật");
                put(70, "Số bị can VKS tạm đình chỉ không có căn cứ pháp luật");
                put(71, "Số vụ án vi phạm trong việc quyết định truy tố");
                put(72, "Số vụ án có vi phạm khác trong giai đoạn khởi tố, điều tra, truy tố các vụ án hình sự");
                put(73, "Số lệnh, quyết định áp dụng, thay đổi, huỷ bỏ biện pháp ngăn chặn có vi phạm");
                put(74, "Trong đó: - Cơ quan điều tra");
                put(75, "                       Trong đó: Số lệnh bắt người bị giữ trong trường hợp khẩn cấp");
                put(76, "                  - Cơ quan Viện kiểm sát");
                put(77, "                  - Cơ quan Tòa án");
                put(78, "Số lần vi phạm trong việc gửi, tống đạt, thông báo, niêm yết... các lệnh, quyết định áp dụng, thay đổi, hủy bỏ các biện pháp ngăn chặn");
                put(79, "Trong đó: - Cơ quan điều tra");
                put(80, "                  - Cơ quan Viện kiểm sát");
                put(81, "                  - Cơ quan Tòa án");
                put(82, "Số lần vi phạm trong việc thực hiện các biện pháp ngăn chặn");
                put(83, "Số người, bị can quá thời hạn tạm giữ, tạm giam");
                put(84, "Trong đó: - Cơ quan điều tra");
                put(85, "                  - Cơ quan Viện kiểm sát");
                put(86, "                  - Cơ quan Tòa án");
                put(87, "Số lệnh, quyết định của VKS vi phạm thời hạn phê chuẩn");
                put(88, "Số quyết định phê chuẩn hoặc quyết định không phê chuẩn của VKS không có căn cứ pháp luật");
                put(89, "Trong đó:Số quyết định phê chuẩn hoặc quyết định không phê chuẩn lệnh bắt người bị giữ trong trường hợp khẩn cấp");
                put(90, "Số lần vi phạm trong việc gửi, thông báo, niêm yết lệnh, quyết định của VKS");
                put(91, "Số lần vi phạm khác trong việc áp dụng, thay đổi, huỷ bỏ biện pháp ngăn chặn");
                put(92, "Số người, bị can, bị cáo bị áp dụng biện pháp cưỡng chế có vi phạm");
                put(93, "Trong đó: - Số người bị áp dụng biện pháp áp giải");
                put(94, "                  - Số người bị áp dụng biện pháp dẫn giải");
                put(95, "                  - Số bị can, bị cáo bị áp dụng biện pháp kê biên tài sản");
                put(96, "                  - Số người bị áp dụng biện pháp phong toả tài khoản");
                put(97, "Số bị can, bị cáo bị những người có thẩm quyền thuộc CQĐT (thủ trưởng, phó thủ trưởng), Tòa án áp dụng biện pháp kê biên tài sản, phong toả tài khoản nhưng không thông báo ngay cho VKS trước khi thi hành (theo K2 Đ128 và K2 Đ129 BLTTHS)");
                put(98, "Số bị can, bị cáo được những người thuộc Cơ quan có thẩm quyền huỷ bỏ biện pháp kê biên tài sản, phong toả tài khoản không có căn cứ và trái pháp luật (theo Đ130 BLTTHS)");
                put(99, "Trong đó: - Những người có thẩm quyền thuộc CQĐT");
                put(100, "                   Trong đó: Những người có thẩm quyền thuộc CQĐT của công an nhân dân");
                put(101, "                  - Những người có thẩm quyền thuộc Cơ quan Viện kiểm sát");
                put(102, "                  - Những người có thẩm quyền thuộc Cơ quan tòa án");
                put(103, "Số lần vi phạm khác trong việc áp dụng, thay đổi, huỷ bỏ biện pháp cưỡng chế đối với người, bị can, bị cáo");
                put(104, "Số vụ án vi phạm thời hạn chuẩn bị xét xử");
                put(105, "Số quyết định, bản án của Tòa án có vi phạm");
                put(106, "Số vụ án vi phạm về thành phần hội đồng xét xử");
                put(107, "Số vụ án vi phạm về việc tạm ngừng phiên toà");
                put(108, "Số vụ án vi phạm về việc hoãn phiên toà");
                put(109, "Số vụ án vi phạm về giới hạn xét xử");
                put(110, "Số bị cáo HĐXX vi phạm trong việc áp dụng tình tiết tăng nặng TNHS");
                put(111, "Số bị cáo HĐXX vi phạm trong việc áp dụng tình tiết giảm nhẹ TNHS");
                put(112, "Số bị cáo HĐXX vi phạm trong việc áp dụng loại hình phạt, mức hình phạt");
                put(113, "Số vụ án có vi phạm trong việc xử lý vật chứng");
                put(114, "Số vụ án vi phạm về việc bảo đảm quyền bào chữa");
                put(115, "Số lần vi phạm trong việc tống đạt ba, QĐ của Tòa án");
                put(116, "Số lần vi phạm trong việc gửi ba, QĐ cho VKS");
                put(117, "Số vụ án vi phạm trong việc nghị án");
                put(118, "Số bị can, bị cáo VKS rút quyết định truy tố");
                put(119, "Số quyết định rút quyết định truy tố của VKS không có căn cứ pháp luật");
                put(120, "Số lần VKS vi phạm thời hạn chuyển giao hồ sơ cho Tòa án");
                put(121, "Số kháng nghị bị VKS cấp trên rút kháng nghị");
                put(122, "Số vụ án có vi phạm khác trong giai đoạn hoạt động xét xử các vụ án hình sự");
                put(123, "Số quyết định ta gửi cho VKS vi phạm về thời hạn");
                put(124, "Số quyết định việc áp dụng biện pháp xử lý hành chính của Tòa án có vi phạm");
                put(125, "Trong đó: - Số quyết định đưa vào trường giáo dưỡng");
                put(126, "                   - Số quyết định đưa vào cơ sở giáo dục bắt buộc");
                put(127, "                   - Số quyết định đưa vào cơ sở cai nghiện bắt buộc");
                put(128, "Số quyết định vi phạm khác trong việc áp dụng biện pháp xử lý hành chính của Tòa án ");
                put(129, "Số lần vi phạm về trình tự, thủ tục tạm giữ, tạm giam");
                put(130, "Trong đó: - Vi phạm trong tạm giữ");
                put(131, "                  - Vi phạm trong tạm giam");
                put(132, "Số lần vi phạm trong công tác quản lý về tạm giữ, tạm giam");
                put(133, "Trong đó: - Vi phạm trong tạm giữ");
                put(134, "                  - Vi phạm trong tạm giam");
                put(135, "Số lần vi phạm trong công tác giáo dục người bị tạm giữ, tạm giam");
                put(136, "Trong đó: - Vi phạm trong tạm giữ");
                put(137, "                  - Vi phạm trong tạm giam");
                put(138, "Số người VKS ra quyết định huỷ bỏ quyết định tạm giữ trong trường hợp việc tạm giữ không có căn cứ hoặc trái pháp luật");
                put(139, "Số lần vi phạm trong thực hiện chế độ đối với người bị tạm giữ, tạm giam");
                put(140, "Trong đó: - Vi phạm trong tạm giữ");
                put(141, "                  - Vi phạm trong tạm giam");
                put(142, "Số người bị tạm giữ chết (trừ trường hợp do bệnh lý)");
                put(143, "Số người bị tạm giam chết (trừ trường hợp do bệnh lý)");
                put(144, "Trong đó: - Chết do tự sát");
                put(145, "                  - Chết do nguyên nhân khác");
                put(146, "Số người bị tạm giữ phạm tội mới");
                put(147, "Số người bị tạm giam phạm tội mới");
                put(148, "Số người bị tạm giữ trốn");
                put(149, "Số người bị tạm giam trốn");
                put(150, "Số người bị tạm giữ, tạm giam được trả tự do theo K2 Đ22 luật tổ chức VKSND và K2 Đ42 luật thi hành tạm giữ, tạm giam");
                put(151, "Trong đó: - Số người bị tạm giữ");
                put(152, "                  - Số người bị tạm giam");
                put(153, "Số người bị tạm giữ VKS trả tự do không có căn cứ và trái pháp luật");
                put(154, "Số người bị tạm giam VKS trả tự do không có căn cứ và trái pháp luật");
                put(155, "Số quyết định thi hành án có vi phạm");
                put(156, "Số quyết định miễn chấp hành án có vi phạm");
                put(157, "Số quyết định hoãn chấp hành án có vi phạm");
                put(158, "Số quyết định giảm thời hạn chấp hành án có vi phạm");
                put(159, "Số quyết định rút ngắn thời gian thử thách đối với án treo có vi phạm");
                put(160, "Số quyết định tạm đình chỉ chấp hành án có vi phạm");
                put(161, "Số quyết định đình chỉ chấp hành án có vi phạm");
                put(162, "Số quyết định xóa án tích có vi phạm");
                put(163, "Số quyết định cho hưởng thời hiệu có vi phạm");
                put(164, "Số lần vi phạm trong việc áp giải, truy bắt, truy nã đối tượng thi hành án");
                put(165, "Số lần vi phạm về trình tự, thủ tục thi hành án hình sự");
                put(166, "Số lần vi phạm trong công tác về quản lý, giám sát, giáo dục trong thi hành án hình sự");
                put(167, "Trong đó: Số lần vi phạm trong công tác quản lý, giám sát, giáo dục đối tượng tha tù trước thời hạn có điều kiện");
                put(168, "Số hồ sơ quản lý, đề nghị xét, miễn, giảm, đặc xá, rút ngắn thời hạn tha tù trước thời hạn có điều kiện có vi phạm");
                put(169, "Trong đó: Số hồ sơ quản lý, đề nghị rút ngắn thời hạn tha tù trước có điều kiện vi phạm");
                put(170, "Số phạm nhân được tha tù trước thời hạn có điều kiện không đúng quy định của pháp luật");
                put(171, "Số lần vi phạm trong công tác giáo dục đối với phạm nhân và người chấp hành án");
                put(172, "Số lần vi phạm trong việc thực hiện chế độ đối với phạm nhân");
                put(173, "Số phạm nhân chết (trừ trường hợp do bệnh lý)");
                put(174, "Trong đó: - Trại tạm giam");
                put(175, "                  - Trại giam");
                put(176, "                  - Chấp hành án tại nhà tạm giữ");
                put(177, "                  - Chết do tự sát");
                put(178, "                  - Chết do nguyên nhân khác");
                put(179, "Số lần phạm nhân trốn");
                put(180, "Số lần vi phạm trong việc giám sát, giáo dục, nhận xét, đánh giá quá trình cải tạo của người chấp hành án treo, cải tạo không giam giữ, và rút ngắn thời gian thử thách đối với án treo; miễn, giảm thời hạn chấp hành án phạt cải tạo không giam giữ tha tù trước thời hạn có điều kiện");
                put(181, "Số lần vi phạm trong việc thi hành hình phạt quản chế, cấm cư trú, tước một số quyền công dân, cấm đảm nhiệm chức vụ, cấm hành nghề hoặclàm công việc nhất định…");
                put(182, "Trong đó: Cơ quan có thẩm quyền, trách nhiệm");
                put(183, "Số hồ sơ thi hành biện pháp tư pháp có vi phạm");
                put(184, "Số phạm nhân vi phạm pháp luật bị khởi tố hình sự");
                put(185, "Số phạm nhân VKS trả tự do không có căn cứ và trái pháp luật");
                put(186, "Số bản kháng nghị, kiến nghị của VKS ban hành thông qua kiểm sát tạm giữ, tạm giam và thi hành án hình sự không có căn cứ và không được cơ quan bị kiểm sát chấp nhận");
                put(187, "Trong đó: - Nhà tạm giữ");
                put(188, "                  - Trại tạm giam");
                put(189, "                  - Trại giam");
                put(190, "                  - Cơ quan Tòa án");
                put(191, "                  - Cơ quan thi hành án hình sự");
                put(192, "                  - Uỷ ban nhân dân cấp xã");
                put(193, "Số lần vi phạm khác trong thi hành tạm giữ, tạm giam và thi hành án hình sự");
                put(194, "Số quyết định của tòa án gửi cho VKS vi phạm về thời hạn");
                put(195, "Số quyết định việc hoãn, miễn chấp hành, giảm thời hạn, tạm đình chỉ hoặc miễn chấp hành thời gian áp dụng biện pháp xử lý hành chính còn lại có vi phạm");
                put(196, "Trong đó: - Số quyết định hoãn chấp hành");
                put(197, "                  - Số quyết định miễn chấp hành");
                put(198, "                  - Số quyết định giảm thời hạn");
                put(199, "                  - Số quyết định tạm đình chỉ hoặc miễn chấp hành thời gian áp dụng biện pháp xử lý hành chính còn lại của Tòa án");
                put(200, "Số quyết định vi phạm khác về trình tự, thủ tục xem xét, quyết định việc hoãn, miễn chấp hành, giảm thời hạn, tạm đình chỉ hoặc miễn chấp hành phần thời gian áp dụng biện pháp xử lý hành chính còn lại của tòa án");
                put(201, "Số lần vi phạm trong việc cử đăng ký người bào chữa");
                put(202, "Trong đó: Cơ quan quản lý người bào chữa");
                put(203, "Số lần vi phạm trong thực hiện việc bào chữa");
                put(204, "Trong đó: Cơ quan quản lý người bào chữa");
                put(205, "Số người bào chữa bị từ chối cấp giấy chứng nhận bào chữa");
                put(206, "Số người bào chữa bị thu hồi giấy chứng nhận bào chữa do vi phạm hoặc không đủ điều kiện bào chữa");
                put(207, "Số lần vi phạm khác về bào chữa");
                put(208, "Số lần vi phạm trong hoạt động giám định");
                put(209, "Trong đó: Cơ quan có thẩm quyền, trách nhiệm");
                put(210, "Số lần vi phạm trong hoạt động định giá tài sản");
                put(211, "Số lần vi phạm trong hoạt động phiên dịch");
                put(212, "Trong đó: Cơ quan có thẩm quyền, trách nhiệm");
                put(213, "Số lần vi phạm trong hoạt động dịch thuật");
                put(214, "Số lần vi phạm trong hoạt động công chứng");
                put(215, "Trong đó: Cơ quan có thẩm quyền, trách nhiệm");
                put(216, "Số lần cơ quan, cá nhân có trách nhiệm không thực hiện hoặc thực hiện không đầy đủ yêu cầu về giám định, định giá, phiên dịch, dịch thuật, công chứng của các Cơ quan tiến hành tố tụng");
                put(217, "Số lần vi phạm khác về giám định, định giá tài sản, phiên dịch, dịch thuật, công chứng");
                put(218, "Số vụ, việc vi phạm về thẩm quyền giải quyết");
                put(219, "Số vụ, việc vi phạm trong việc thụ lý hoặc không thụ lý đơn khởi kiện, đơn yêu cầu");
                put(220, "Số vụ, việc Tòa án vi phạm thời hạn gửi thông báo thụ lý cho VKS");
                put(221, "Số vụ, việc vi phạm về xác minh, thu thập chứng cứ");
                put(222, "Số vụ, việc vi phạm về lấy lời khai đương sự, người có quyền lợi và nghĩa vụ liên quan");
                put(223, "Số vụ, việc xác định không đúng quan hệ tranh chấp, tư cách người tham gia tố tụng");
                put(224, "Số vụ, việc vi phạm trong việc trưng cầu giám định, định giá tài sản");
                put(225, "Số lần vi phạm trong việc áp dụng, thay đổi, hủy bỏ biện pháp khẩn cấp tạm thời");
                put(226, "Số vụ, việc vi phạm trong việc hòa giải hoặc đối thoại");
                put(227, "Số vụ, việc Tòa án vi phạm thời hạn chuyển hồ sơ cho VKS");
                put(228, "Số vụ, việc vi phạm về thời hạn chuẩn bị xét xử  ");
                put(229, "Số bản án, quyết định Tòa án gửi cho VKS không đúng thời hạn");
                put(230, "Số bản án, quyết định của tòa án có vi phạm  ");
                put(231, "Số vụ, việc vi phạm trong việc đính chính, sửa chữa, bổ sung nội dung bản án");
                put(232, "Số vụ, việc vi phạm trong việc cấp, tống đạt, thông báo, niêm yết các văn bản tố tụng");
                put(233, "Số vụ, việc có vi phạm trong việc thực hiện các quy định về án phí, lệ phí và các chi phí tố tụng khác");
                put(234, "Số vụ, việc vi phạm các quy định tại phiên toà sơ thẩm hoặc phiên họp sơ thẩm");
                put(235, "Số vụ, việc vi phạm các quy định tại phiên toà phúc thẩm hoặc phiên họp phúc thẩm");
                put(236, "Số vụ, việc vi phạm các quy định tại phiên toà hoặc phiên họp giám đốc thẩm, tái thẩm");
                put(237, "Số vụ, việc VKS không thực hiện quyền kiến nghị về QĐ áp dụng, thay đổi, huỷ bỏ biện pháp khẩn cấp tạm thời của Tòa án");
                put(238, "Số vụ, việc VKS không thực hiện quyền kiến nghị về việc ta trả lại đơn khởi kiện, đơn yêu cầu");
                put(239, "Số lần VKS vi phạm thời hạn chuyển giao hồ sơ cho Tòa án");
                put(240, "Số kháng nghị bị VKS cấp trên rút kháng nghị");
                put(241, "Số lần có vi phạm khác trong thụ lý, giải quyết vụ, việc dân sự, HNGĐ; KDTM; lao động; hành chính.");
                put(242, "Số lần vi phạm trong việc tiếp nhận, thụ lý đơn yêu cầu thi hành án");
                put(243, "Số việc có vi phạm trong thông báo, niêm yết công khai các quyết định về thi hành án");
                put(244, "Số quyết định về thi hành án dân sự có vi phạm");
                put(245, "Số quyết định thi hành án gửi cho VKS vi phạm về thời hạn");
                put(246, "Số việc vi phạm về việc phân loại, xác minh điều kiện thi hành án");
                put(247, "Số việc vi phạm trong việc uỷ thác và nhận uỷ thác thi hành án ");
                put(248, "Số việc vi phạm trong việc hoãn thi hành án");
                put(249, "Số việc vi phạm trong việc tạm đình chỉ thi hành án");
                put(250, "Số việc vi phạm trong việc đình chỉ thi hành án");
                put(251, "Số việc vi phạm trong việc áp dụng các biện pháp cưỡng chế thi hành án");
                put(252, "Trong đó:  Số việc vi phạm trong việc kê biên, định giá, bán đấu giá tài sản");
                put(253, "Số việc vi phạm việc áp dụng biện pháp bảo đảm thi hành án");
                put(254, "Số việc vi phạm chuyển giao quyền, nghĩa vụ thi hành án");
                put(255, "Số việc vi phạm về áp dụng các biện pháp khẩn cấp tạm thời");
                put(256, "Số việc vi phạm thi hành khoản tịch thu sung quỹ nhà nước, hoàn trả tiền, tài sản kê biên, tạm giữ trong bản án");
                put(257, "Số việc vi phạm trong việc cơ quan THADS thi hành án đối với khoản thu nộp ngân sách nhà nước");
                put(258, "Số việc vi phạm trong việc xử lý tài sản, vật chứng");
                put(259, "Số việc vi phạm trong việc lập hồ sơ xét miễn, giảm tiền thi hành án");
                put(260, "Số việc vi phạm trong việc thu, quản lý, xử lý tiền, tài sản thi hành án");
                put(261, "Số việc vi phạm trong việc không ra quyết định thu phí thi hành án");
                put(262, "Số bản án, quyết định Tòa án vi phạm thời hạn chuyển giao cho cơ quan thi hành án");
                put(263, "Số quyết định buộc thi hành án hành chính của tòa án có vi phạm");
                put(264, "Số việc Tòa án có vi phạm trong việc xét miễn, giảm tiền thi hành án");
                put(265, "Số việc có vi phạm khác trong THA dân sự và THA hành chính");
                put(266, "Số lần vi phạm trong việc tiếp công dân");
                put(267, "Trong đó: - Cơ quan điều tra");
                put(268, "                  - Cơ quan Viện kiểm sát");
                put(269, "                  - Cơ quan Tòa án");
                put(270, "                  - Cơ quan thi hành án");
                put(271, "                  - Cơ quan khác");
                put(272, "Số lần vi phạm trong việc tiếp nhận, phân loại, thụ lý đơn");
                put(273, "Trong đó: - Cơ quan điều tra");
                put(274, "                  - Cơ quan Viện kiểm sát");
                put(275, "                  - Cơ quan Tòa án");
                put(276, "                  - Cơ quan thi hành án");
                put(277, "                  - Cơ quan khác");
                put(278, "Số lần có vi phạm về việc thực hiện trách nhiệm bảo vệ người tố cáo");
                put(279, "Trong đó: - Cơ quan điều tra");
                put(280, "                  - Cơ quan Viện kiểm sát");
                put(281, "                  - Cơ quan Tòa án");
                put(282, "                  - Cơ quan thi hành án");
                put(283, "                  - Cơ quan khác");
                put(284, "Số đơn có vi phạm về trình tự, thủ tục giải quyết");
                put(285, "Trong đó: - Cơ quan điều tra");
                put(286, "                  - Cơ quan Viện kiểm sát");
                put(287, "                  - Cơ quan Tòa án");
                put(288, "                  - Cơ quan thi hành án");
                put(289, "                  - Cơ quan khác");
                put(290, "Số đơn có vi phạm thẩm quyền thụ lý giải quyết đơn");
                put(291, "Trong đó: - Cơ quan điều tra");
                put(292, "                  - Cơ quan Viện kiểm sát");
                put(293, "                  - Cơ quan Tòa án");
                put(294, "                  - Cơ quan thi hành án");
                put(295, "                  - Cơ quan khác");
                put(296, "Số việc vi phạm về nội dung giải quyết");
                put(297, "Trong đó: - Cơ quan điều tra");
                put(298, "                   - Cơ quan Viện kiểm sát");
                put(299, "                   - Cơ quan Tòa án");
                put(300, "                   - Cơ quan thi hành án");
                put(301, "                   - Cơ quan khác");
                put(302, "Số việc kiểm sát giải quyết khiếu nại, tố cáo có vi phạm");
                put(303, "Số bản kết luận, kiến nghị, kháng nghị của VKS ban hành thông qua hoạt động kiểm sát việc giải quyết KNTC đối với các Cơ quan tư pháp không có căn cứ và không được Cơ quan bị kiểm sát chấp nhận.");
                put(304, "Số lần vi phạm khác trong thụ lý, giải quyết khiếu nại, tố cáo về tư pháp");
                put(305, "Số người bị xử lý kỷ luật, xử lý hành chính");
                put(306, "Trong đó: - Cơ quan công an");
                put(307, "                  - Cơ quan Viện kiểm sát");
                put(308, "                  - Cơ quan Tòa án");
                put(309, "                  - Cơ quan thi hành án");
                put(310, "                  - Cơ quan khác");
                put(311, "Số người bị khởi tố bị can");
                put(312, "Trong đó: - Cơ quan công an");
                put(313, "                  - Cơ quan Viện kiểm sát");
                put(314, "                  - Cơ quan Tòa án");
                put(315, "                  - Cơ quan thi hành án");
                put(316, "                  - Cơ quan khác");
                put(317, "Số người VKS yêu cầu CQĐT khởi tố thông qua hoạt động kiểm sát");
                put(318, "Số bị can VKS khởi tố thông qua hoạt động kiểm sát");
            }};
        }
    }
}
